on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

env:
    REGISTRY_NAME: docker.io
    IMAGE_OWNER: oconnormi

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          username: ${{ env.IMAGE_OWNER }} 
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          make image IMAGE_REGISTRY=${{ env.REGISTRY_NAME }} IMAGE_TAG=${{ github.sha }}
          make push IMAGE_REGISTRY=${{ env.REGISTRY_NAME }} IMAGE_TAG=${{ github.sha }}
          make image IMAGE_REGISTRY=${{ env.REGISTRY_NAME }} IMAGE_TAG=latest
          make push IMAGE_REGISTRY=${{ env.REGISTRY_NAME }} IMAGE_TAG=latest
